import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers"; //

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create The Next Gen Alpha",
  description: "Generated by Your Mom!",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
    <body className="min-h-full flex flex-col">
      <Providers>        
        <div className="min-h-full">          
          {children}
        </div>
      </Providers>
    </body>
    </html>
  );
}
